### ISSUE TITLE
Some clarifications re: spec

### ISSUE THREAD

**Issue by ggoodman** [josephg/json1#1]
Hi @josephg and welcome back :-)

I took a quick read-through of the spec and think the pick-up / put-down concept is really novel and clever. Here are some questions and thoughts:

**Pick-up and put-down across ops**
With regards to the pick-up 'slots' can you clarify whether a valid op may leave a sub-tree in suspense in the slot storage? In other words, can I have a pick-up operation to a named / numbered register that does not have a corresponding put-down operation in the same op?

It seems to me that allowing this sort of behaviour would just be asking for crazy corner-cases and challenges down the road. An alternative would be to encourage consumers of the api to create their own 'storage areas' within the `json` tree for disassociated trees if and when their app logic requires it.

So, assuming the behaviour is disallowed, that means some stronger validation can be created for ops and you avoid the issue of potential conflicts on 'pick-up' operations to the same slot.

**List splicing vs overwriting**
In your example of moving something between two items in a list, the item is inserted. Are the semantics to splice the item in or to overwrite the item at that position? It seems to me (perhaps naively) that in the former case, overwriting items will be non-trivial (or the pick-up/delete operation in a list context needs to be specialized to splice vs set to `undefined` or `delete`) while in the latter case, inserting items into the middle of a list will be non-trivial. What are your thoughts?

**Comment by josephg** [comment]
Thanks :D

I'll clarify this stuff in the spec but:

**Pick-up and put-down across ops**
Yeah the 'slot storage' is only temporary. Everything that gets picked up must be put down exactly once. (Hm, we could allow its use to copy items, but I think semantically it'd end up being the same as just manually inserting a deep copy).

**List splicing vs overwriting**
Items inserted into lists are spliced in. (This is the same behaviour as json0). I figure if you're using a list, thats probably the behaviour you want. (But you're super right - the transform logic is *way* more complicated this way). If you want to replace items in a list instead of splicing them in and out, you can implement that by filling your list with nulls and have your operation replace the null with your new value instead of just inserting your new value.
